# Generated by Django 4.2.1 on 2024-06-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='pinned_date',
            field=models.DateField(blank=True, null=True, verbose_name='Pinned Date'),
        ),
    ]
