# Generated by Django 4.2.1 on 2024-06-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0003_alter_todo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-updated_date'], 'verbose_name': 'Todo', 'verbose_name_plural': 'Todos'},
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='pinned_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Pinned Date'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Date'),
        ),
    ]
