# Generated by Django 4.2.1 on 2024-06-17 18:11

from django.db import migrations, models
import notes.models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=notes.models.note_image_upload_to),
        ),
    ]
