# Generated by Django 4.2.1 on 2024-06-18 06:24

from django.db import migrations, models
import notes.models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_note_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='image',
            field=models.ImageField(default='notes.jpg', upload_to=notes.models.note_image_upload_to),
        ),
    ]
